version: '3.7'
services:
  dbnode:
    image: mariadb:latest
    restart: always
    environment:
      #      tagged values exist in .env file, .env file added to .gitignore
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_TCP_PORT: 3306
    volumes:
      - './docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql'
#      - ${PWD}/mariadb:/var/lib/mysql
#    networks:
#      - back
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
#    networks:
#      - back
  webserver:
    build:
      context: .
      dockerfile: docker/Dockerfile-php7.4-xdebug2.9-pdo_mysql-rewrite_enabled
    image: phpstorm/php-74-apache-xdebug-29:latest
    depends_on:
      - dbnode
#    image: phpstorm/php-73-apache-xdebug-27:latest
    ports:
      - "80:80"
    volumes:
      - './:/var/www/html/'
#      - './php/conf.d/docker-php-ext-pdo.ini:/usr/local/etc/php/conf.d/docker-php-ext-pdo.ini'
#      - './php/conf.d/docker-php-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-xdebug.ini'
#    networks:
#      - front
#      - back
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
#networks:
#  front:
#  back: